openapi: 3.0.0
info:
  title: e-Test 3.0 - Personal Data Glossary
  version: 1.0.1
  description: "Definitions and standardization of personal data types used in e-Test 3.0."
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths:
  /person:
    post:
      summary: Create a new person
      operationId: createPerson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Person created successfully
    put:
      summary: Update an existing person
      operationId: updatePerson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: Person updated successfully
  /person/{id}:
    patch:
      summary: Modify specific fields of a person
      operationId: modifyPerson
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Partial update of person fields
      responses:
        '200':
          description: Person modified successfully
components:
  schemas:
    Person:
      type: object
      properties:
        firstName:
          type: string
          description: Person's first name.
        lastName:
          type: string
          description: Person's last name.
        birthDate:
          type: string
          format: date
          description: Birthdate in YYYY-MM-DD format.
        gender:
          $ref: '#/components/schemas/GenderCode'
        address:
          type: string
          description: Full residential address.
        civilStatus:
          $ref: '#/components/schemas/CivilStatusTypeCode'
        phoneNumber:
          type: string
          description: Person's contact phone number in international format (e.g. +32 475 12 34 56).
        householdRelation:
          $ref: '#/components/schemas/HouseholdRelationTypeCode'
      required:
        - firstName
        - lastName
        - birthDate
        - gender
        - address
    GenderCode:
      description: 'Gender of a person according to ISO 5218 standard: 0 = Unknown, 1 = Male, 2 = Female'
      type: integer
      enum:
        - 0
        - 1
        - 2
    HouseholdRelationTypeCode:
      description: "Relationship of a household member to the household reference person as defined by the National Register."
      type: integer
      minimum: 1
      maximum: 99
    CivilStatusTypeCode:
      description: "Civil status of a person as defined by the National Register."
      type: integer
      minimum: 1
      maximum: 99

